--- #YAML:1.0
name:               Music-Tag-LyricsFetcher
version:            0.4101
abstract:           Plugin module for Music::Tag to fetch lyrics use Lyrics::Fetcher
author:
    - Edward Allen <ealleniii@cpan _dot_ org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Lyrics::Fetcher:      0.005
    Lyrics::Fetcher::LyricWiki:  0.01
    Music::Tag:           0.4101
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
